In [1]:
import numpy as np

In [58]:
class Matrix:
    
    def __init__(self, rows: int, cols: int) -> None:
        self.rows = rows
        self.cols = cols
     
    def fill(self) -> np.ndarray:
        matrix = np.zeros((self.rows, self.cols), int)
        for i in range(self.rows):
            for j in range(self.cols):
                matrix[i][j] = int(input())
        return matrix
    
    def summ(self, matrix: list, matrix2: list) -> np.ndarray:
        return matrix + matrix2
    
    def diff(self, matrix: list, matrix2: list) -> np.ndarray:
        return matrix - matrix2
        
    
    def muilt(self, matrix: list,  matrix2: list) -> np.ndarray:
        matrix_result =  np.dot(matrix, matrix2)
        return matrix_result
    
    def mat_size(self, matrix: list) -> int:
        return matrix.size

In [42]:
mx = Matrix(3, 3)

In [27]:

m1_a = mx.fill()
m1_b = mx.fill()

1
2
4
7
5
-2
-2
1
3
-1
0
3
2
-6
1
-7
1
5


In [29]:
m2_a = mx.fill()
m2_b = mx.fill()

0
3
4
-7
1
-2
2
-1
3
1
2
4
7
0
-2
-3
-2
5


In [30]:
m3_a = mx.fill()
m3_b = mx.fill()

5
2
9
7
0
-2
-2
1
6
1
-2
1
7
5
-2
-2
8
3


In [31]:
m4_a = mx.fill()
m4_b = mx.fill()

1
-2
8
7
5
-2
-2
3
0
0
2
4
1
-3
-2
-2
1
3


In [32]:
m5_a = mx.fill()
m5_b = mx.fill()

9
2
4
7
5
-5
6
-2
3
8
2
4
0
1
-3
-2
1
6


In [21]:
mx.summ(m1)

8
2
4
0
1
-3
-2
1
6


array([[17,  4,  8],
       [ 7,  6, -8],
       [ 4, -1,  9]])

Сумма матриц А + В:
1)[[ 0,  2,  7],
   [ 9, -1, -1],
   [-9,  2,  8]]
   
2)[[ 1,  5,  8],
   [ 0,  1, -4],
   [-1, -3,  8]]
   
3)[[ 6,  0, 10],
   [14,  5, -4],
   [-4,  9,  9]]
   
4)[[ 1,  0, 12],
   [ 8,  2, -4],
   [-4,  4,  3]]
   
5)[[17,  4,  8],
   [ 7,  6, -8],
   [ 4, -1,  9]]

In [36]:
mx.diff(m5_b, m5_a)

array([[-1,  0,  0],
       [-7, -4,  2],
       [-8,  3,  3]])

Разность матриц В - А:
1)[[ -2,  -2, -1],
   [ -5, -11,  3],
   [ -5,   0,  2]]
   
2)[[ 1, -1,  0],
   [14, -1,  0],
   [-5, -1,  2]]
   
3)[[-4, -4, -8],
   [ 0,  5,  0],
   [ 0,  7, -3]]
   
4)[[-1,  4, -4],
   [-6, -8,  0],
   [ 0, -2,  3]
   
5) [[-1,  0,  0],
    [-7, -4,  2],
    [-8,  3,  3]]

In [43]:
mx_c = Matrix(3, 2)

In [45]:
m1_c = mx_c.fill()
m2_c = mx_c.fill()

-2
3
4
0
7
-1
-3
2
0
4
-1
7


In [46]:
m3_c = mx_c.fill()
m4_c = mx_c.fill()
m5_c = mx_c.fill()

-2
3
4
5
0
-1
0
3
5
-4
7
-1
-2
0
4
8
1
-1


In [51]:
mx_c.muilt(m5_a, m5_c)

array([[ -6,  12],
       [  1,  45],
       [-17, -19]])

Произведение матриц A*C
1)[[34, -1],
   [-8, 23],
   [29, -9]]
   
2)[[ -4,  40],
   [ 23, -24],
   [ -9,  21]]
   
3)[[ -2,  16],
   [-14,  23],
   [  8,  -7]]
   
4)[[ 46,   3],
   [ 11,   3],
   [ 15, -18]]
   
5)[[ -6,  12],
   [  1,  45],
   [-17, -19]]

In [56]:
mx_c.muilt(mx.muilt(m5_a, m5_b), m5_c)

array([[ 22, 138],
       [-93, 129],
       [ 16,  56]])

Произведение матриц А*В*С
1)[[ 193, -100],
   [ -50,   35],
   [  92,  -61]]
   
2)[[ -41,   84],
   [  22, -308],
   [  17,  139]]
   
3)[[ 286,  335],
   [-142, -118],
   [ 242,  250]]
   
4)[[ 304, -150],
   [  69,   27],
   [-163,   75]]
   
5)[[ 22, 138],
   [-93, 129],
   [ 16,  56]]

In [57]:
type(mx.diff(m5_b, m5_a))

numpy.ndarray